#ifndef KEYBOARD_H
#define KEYBOARD_H
#include "../config.h"

// defining scan codes
#define SCAN_CODE_PRESSED_ESCAPE 0x01
#define SCAN_CODE_PRESSED_1 0x2
#define SCAN_CODE_PRESSED_2 0x3
#define SCAN_CODE_PRESSED_3 0x4
#define SCAN_CODE_PRESSED_4 0x5
#define SCAN_CODE_PRESSED_5 0x6
#define SCAN_CODE_PRESSED_6 0x7
#define SCAN_CODE_PRESSED_7 0x8
#define SCAN_CODE_PRESSED_8 0x9
#define SCAN_CODE_PRESSED_9 0xA
#define SCAN_CODE_PRESSED_0 0xB
#define SCAN_CODE_PRESSED_DASH 0xC
#define SCAN_CODE_PRESSED_EQUALS 0xD
#define SCAN_CODE_PRESSED_BACKSPACE 0xE
#define SCAN_CODE_PRESSED_TAB 0xF
#define SCAN_CODE_PRESSED_Q 0x10
#define SCAN_CODE_PRESSED_W 0x11
#define SCAN_CODE_PRESSED_E 0x12
#define SCAN_CODE_PRESSED_R 0x13
#define SCAN_CODE_PRESSED_T 0x14
#define SCAN_CODE_PRESSED_Y 0x15
#define SCAN_CODE_PRESSED_U 0x16
#define SCAN_CODE_PRESSED_I 0x17
#define SCAN_CODE_PRESSED_O 0x18
#define SCAN_CODE_PRESSED_P 0x19
#define SCAN_CODE_PRESSED_OPEN_SQUARE_BRACKET 0x1A
#define SCAN_CODE_PRESSED_CLOSE_SQUARE_BRACKET 0x1B
#define SCAN_CODE_PRESSED_RETURN 0x1C
#define SCAN_CODE_PRESSED_CTRL 0x1D
#define SCAN_CODE_PRESSED_A 0x1E
#define SCAN_CODE_PRESSED_S 0x1F
#define SCAN_CODE_PRESSED_D 0x20
#define SCAN_CODE_PRESSED_F 0x21
#define SCAN_CODE_PRESSED_G 0x22
#define SCAN_CODE_PRESSED_H 0x23
#define SCAN_CODE_PRESSED_J 0x24
#define SCAN_CODE_PRESSED_K 0x25
#define SCAN_CODE_PRESSED_L 0x26
#define SCAN_CODE_PRESSED_SEMICOLON 0x27
#define SCAN_CODE_PRESSED_APOSTROPHE 0x28
#define SCAN_CODE_PRESSED_GRAVIS 0x29
#define SCAN_CODE_PRESSED_SHIFT_LEFT 0x2A
#define SCAN_CODE_PRESSED_BACKSLASH 0x2B
#define SCAN_CODE_PRESSED_Z 0x2C
#define SCAN_CODE_PRESSED_X 0x2D
#define SCAN_CODE_PRESSED_C 0x2E
#define SCAN_CODE_PRESSED_V 0x2F
#define SCAN_CODE_PRESSED_B 0x30
#define SCAN_CODE_PRESSED_N 0x31
#define SCAN_CODE_PRESSED_M 0x32
#define SCAN_CODE_PRESSED_COMMA 0x33
#define SCAN_CODE_PRESSED_DOT 0x34
#define SCAN_CODE_PRESSED_SLASH 0x35
#define SCAN_CODE_PRESSED_SHIFT_RIGHT 0x36
#define SCAN_CODE_PRESSED_ALT 0x38
#define SCAN_CODE_PRESSED_SPACE 0x39
#define SCAN_CODE_PRESSED_CAPS_LOCK 0x3A
#define SCAN_CODE_PRESSED_F1 0x3B
#define SCAN_CODE_PRESSED_F2 0x3C
#define SCAN_CODE_PRESSED_F3 0x3D
#define SCAN_CODE_PRESSED_F4 0x3E
#define SCAN_CODE_PRESSED_F5 0x3F
#define SCAN_CODE_PRESSED_F6 0x40
#define SCAN_CODE_PRESSED_F7 0x41
#define SCAN_CODE_PRESSED_F8 0x42
#define SCAN_CODE_PRESSED_F9 0x43
#define SCAN_CODE_PRESSED_F10 0x44


// if function returns 0 it means that any key wasn't pressed/released
unsigned char get_keyboard_scancode();

#endif